using DapperLabs_Lab2.Data;
using DapperLabs_Lab2.DTOs;

namespace DapperLabs_Lab2.Mappings
{
    // [API] Mapping Extensions - Convert between entities and API DTOs
    public static class MappingExtensions
    {
        // [API] Entity to DTO mapping for API responses
        // Customer mappings
        public static CustomerDto ToDto(this Customer customer)
        {
            return new CustomerDto
            {
                Id = customer.Id,
                Name = customer.Name,
                Email = customer.Email,
                Balance = customer.Balance, // [API] Calculated property for API
                Invoices = customer.Invoices?.Select(i => i.ToDto()).ToList(), // [API] Map nested objects
                PhoneNumbers = customer.PhoneNumbers?.Select(p => p.ToDto()).ToList()
            };
        }

        // [API] CreateDto to Entity mapping for POST requests
        public static Customer ToEntity(this CreateCustomerDto dto)
        {
            return new Customer
            {
                Name = dto.Name,
                Email = dto.Email
                // [API] No ID - auto-generated by database
            };
        }

        // [API] UpdateDto to Entity mapping for PUT requests
        public static void UpdateEntity(this UpdateCustomerDto dto, Customer customer)
        {
            customer.Name = dto.Name;
            customer.Email = dto.Email;
            // [API] ID not updated - comes from route parameter
        }

        // Invoice mappings
        public static InvoiceDto ToDto(this Invoice invoice)
        {
            return new InvoiceDto
            {
                Id = invoice.Id,
                InvoiceNumber = invoice.InvoiceNumber,
                CustomerId = invoice.CustomerId,
                InvoiceDate = invoice.InvoiceDate,
                Amount = invoice.Amount
            };
        }

        public static Invoice ToEntity(this CreateInvoiceDto dto)
        {
            return new Invoice
            {
                InvoiceNumber = dto.InvoiceNumber,
                CustomerId = dto.CustomerId,
                InvoiceDate = dto.InvoiceDate,
                Amount = dto.Amount
            };
        }

        public static void UpdateEntity(this UpdateInvoiceDto dto, Invoice invoice)
        {
            invoice.InvoiceNumber = dto.InvoiceNumber;
            invoice.InvoiceDate = dto.InvoiceDate;
            invoice.Amount = dto.Amount;
            // CustomerId cannot be changed in update
        }

        // TelephoneNumber mappings
        public static TelephoneNumberDto ToDto(this TelephoneNumber telephoneNumber)
        {
            return new TelephoneNumberDto
            {
                Id = telephoneNumber.Id,
                CustomerId = telephoneNumber.CustomerId,
                Type = telephoneNumber.Type,
                Number = telephoneNumber.Number
            };
        }

        public static TelephoneNumber ToEntity(this CreateTelephoneNumberDto dto)
        {
            return new TelephoneNumber
            {
                CustomerId = dto.CustomerId,
                Type = dto.Type,
                Number = dto.Number
            };
        }

        public static void UpdateEntity(this UpdateTelephoneNumberDto dto, TelephoneNumber telephoneNumber)
        {
            telephoneNumber.Type = dto.Type;
            telephoneNumber.Number = dto.Number;
            // CustomerId cannot be changed in update
        }
    }
}
